version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/proctor
    depends_on:
      - mongo
    ports:
      - "4000:4000"
